#!/bin/bash

export PATH="${PATH}:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

### Global Vars Def
BASE_DIR="$(cd $(dirname $0); pwd)"
LOG_DIR="${BASE_DIR}/logs"
LOGFILE="${BASE_DIR}/logs/${0##*/}.log"

PATH_TARBALL="${BASE_DIR}/opt/balls"
PATH_EXTRACT="${BASE_DIR}/opt/extract"

PATH_ESOP="/usr/local/eyou/toolmail"

PATH_INSTALL="${PATH_ESOP}/opt"



[ "$1" == "clean" ] && {
   rm -rf "${PATH_EXTRACT}"
   exit 0
}

# Command Def
CMD_UNTAR_GZ="tar -zxf"
CMD_MAKE="make"


OS_BIT=$(getconf LONG_BIT 2>&-)
[ -z "${OS_BIT}" -o ! -z "${OS_BIT//[0-9]}" ] && OS_BIT="32"



# Global Func Def

# - check_rc
check_rc() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  succed!  ${*} " | tee -a $LOGFILE
  else
        echo -e " -- $(date +%F_%T)  failed!  ${*} " | tee -a $LOGFILE
        exit 1
  fi
}


# Build Func Def


# -- build_redis
build_redis() {
  local filename="redis-2.6.16.tar.gz"  dirname="redis-2.6.16"

  $CMD_UNTAR_GZ $PATH_TARBALL/$filename -C $PATH_EXTRACT
  cd $PATH_EXTRACT/$dirname

  $CMD_MAKE
  check_rc "make $filename"

  PREFIX=$PATH_INSTALL $CMD_MAKE install
  check_rc "install $filename"
}



### Main Body Begin ...

echo -e "\n -- $(date +%F_%T) -- BUILD START -- \n\n" >> $LOGFILE

if [ -d "${PATH_ESOP}" ]; then
  rm -rf "${PATH_ESOP}"
  check_rc "remove ${PATH_ESOP}"
fi

if [ -d "${PATH_EXTRACT}" ]; then
  rm -rf "${PATH_EXTRACT}"
  check_rc "remove ${PATH_EXTRACT}"
fi

mkdir -p "${LOG_DIR}" "${PATH_EXTRACT}"


build_redis


echo -e "\n -- $(date +%F_%T) -- BUILD END -- \n\n" >> $LOGFILE
