#!/bin/bash

export PATH="${PATH}:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

### Global Vars Def
BASE_DIR="$(cd $(dirname $0); pwd)"
LOG_DIR="${BASE_DIR}/logs"
LOGFILE="${BASE_DIR}/logs/${0##*/}.log"

PATH_TARBALL="${BASE_DIR}/opt/balls"
PATH_EXTRACT="${BASE_DIR}/opt/extract"

PATH_ESOP="/usr/local/eyou/toolmail"

mkdir -p "${PATH_TARBALL}" "${PATH_EXTRACT}" "${LOG_DIR}"


[ "$1" == "clean" ] && {
   rm -rf "${PATH_EXTRACT}"
   exit 0
}

# Command Def

CMD_UNTAR="tar -xf"
CMD_UNTAR_BZ2="tar -jxf"
CMD_UNTAR_GZ="tar -zxf"
CMD_MAKE="make"
CMD_MAKE_J="make -j 2"


# Global Func Def

# - check_rc
check_rc() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  succed!  ${*} " | tee -a $LOGFILE
  else
        echo -e " -- $(date +%F_%T)  failed!  ${*} " | tee -a $LOGFILE
        exit 1
  fi
}

# -- build_esopserver_code
build_esopserver_code() {
  local filename="esopserver-1.0-beta1.tgz"  dirname="esopserver-1.0-beta1"

  $CMD_UNTAR_GZ $PATH_TARBALL/$filename -C $PATH_EXTRACT

  cp -a $PATH_EXTRACT/$dirname/*  $PATH_ESOP/
  check_rc "install $dirname to $PATH_ESOP"
}

install_sh() {
  local sh1="sbin/init_install" sql1="sql/db_creation_eyou_monitor.sql" sql2="sql/db_init_eyou_monitor.sql"

  mkdir -p $PATH_ESOP/tmp_install/sbin/
  check_rc "create $PATH_ESOP/tmp_install/sbin/"

  cp $PATH_EXTRACT/"$sh1" "$PATH_ESOP/tmp_install/sbin/"
  check_rc "install $sh1 to $PATH_ESOP/tmp_install/sbin/"

  mkdir -p $PATH_ESOP/tmp_install/sql/
  check_rc "create $PATH_ESOP/tmp_install/sql/"

  cp $PATH_EXTRACT/"$sql1" $PATH_EXTRACT/"${sql2}" "$PATH_ESOP/tmp_install/sql/"
  check_rc "install $sql1 $sql2 to $PATH_ESOP/tmp_install/sql/"
}

### Main Body Begin ...

echo -e "\n -- $(date +%F_%T) -- BUILD START -- \n\n" >> $LOGFILE
build_esopserver_code
install_sh
echo -e "\n -- $(date +%F_%T) -- BUILD END -- \n\n" >> $LOGFILE
