#!/bin/bash

basedir="$(cd $(dirname $0);pwd)"


# Func Def
check_rc() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  succed!  ${*}"
  else
        echo -e " -- $(date +%F_%T)  failed!  ${*}"; exit 1
  fi
}


### Main Body Begin ...


if [ "$(id -u)" != "0" ]; then
  echo " root privileges required! "
  exit 1
fi

destdir="/data/esop_codes"
specfile="${basedir}/esop.spec"
initfile="${basedir}/esop.init"
name=$(awk -F: '($1~/Name/){print $2}'  $specfile 2>&-|tr -d ' \t')
version=$(awk -F: '($1~/Version/){print $2}' $specfile 2>&-|tr -d ' \t')
source0=$(awk -F: '($1~/Source0/){print $2}' $specfile 2>&-|tr -d ' \t')
source1=$(awk -F: '($1~/Source1/){print $2}' $specfile 2>&-|tr -d ' \t')

# publish agent tarball codes
mkdir -p $basedir/${name}-${version}
check_rc "create directory $basedir/$name-$version"

cp -a "${basedir}"/{bin,sbin,conf,docs,handler,log,opt,plugin,share,tmp} $basedir/${name}-${version}/
check_rc "copy bin sbin conf docs handler log opt plugin share tmp"

cd $basedir
check_rc "chaning into $basedir"

tar -czf "${source0}" ${name}-${version}
check_rc "make tarball on $name-$version: $source0"

rm -rf $basedir/${name}-${version}
check_rc "remove $basedir/$name-$version"

filename="$basedir/${source0}"
ls "${filename}" >/dev/null 2>&1
check_rc "check path: ${filename}"

/bin/cp -f "${filename}" "${destdir}/"
check_rc "copy to ${destdir}/${filename##*/}"

/bin/rm -f "${filename}"
check_rc "remove local $filename"

# publish agent spec file
/bin/cp -f "${specfile}" "${destdir}/"
check_rc "copy to ${destdir}/${specfile##*/}"

# publish agent init file
/bin/cp -f "${initfile}" "${destdir}/"
check_rc "copy to ${destdir}/${initfile##*/}"

# publish esop_agent_build
agent_build_dir="esop_agent_build"
/bin/rm -rf "${destdir}"/rpm_workdir/${agent_build_dir}
check_rc "remove nfs remote: ${destdir}/rpm_workdir/${agent_build_dir}"

/bin/cp -a "${basedir}/${agent_build_dir}" ${destdir}/rpm_workdir/
check_rc "copy to ${destdir}/rpm_workdir/${agent_build_dir}"

# publish esop_plugin_build
plugin_build_dir="esop_plugin_build"
/bin/rm -rf "${destdir}"/rpm_workdir/${plugin_build_dir}
check_rc "remove nfs remote: ${destdir}/rpm_workdir/${plugin_build_dir}"

/bin/cp -a "${basedir}/${plugin_build_dir}" ${destdir}/rpm_workdir/
check_rc "copy to ${destdir}/rpm_workdir/${plugin_build_dir}"

# publish esop_server_build
server_build_dir="esop_server_build"
/bin/rm -rf $destdir/rpm_workdir/$server_build_dir
check_rc "remove nfs remote: ${destdir}/rpm_workdir/$server_build_dir"

/bin/cp -a $basedir/$server_build_dir ${destdir}/rpm_workdir/
check_rc "copy to ${destdir}/rpm_workdir/$server_build_dir"
