#!/bin/bash

basedir="$(cd $(dirname $0);pwd)"


# Func Def
check_rc() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  succed!  ${*}"
  else
        echo -e " -- $(date +%F_%T)  failed!  ${*}"; exit 1
  fi
}


### Main Body Begin ...
if [ "$1" == "server" ]; then
  filename="${basedir}/esop_server_build/2_src/init/init_install"
  specfile="${basedir}/esopserver.spec"
  initfile="${basedir}/esopserver.init"
  destdir="/data/esop_codes/server-side"

  /bin/cp -f ${filename} ${destdir}/sbin/
  check_rc "copy to ${destdir}/sbin/${filename##*/}"

  /bin/cp -f ${specfile} ${destdir}/
  check_rc "copy to ${destdir}/${specfile##*/}"

  /bin/cp -f ${initfile} ${destdir}/
  check_rc "copy to ${destdir}/${initfile##*/}"

  exit
elif [ "$1" == "agent" ]; then
  specfile="${basedir}/esop.spec"
  initfile="${basedir}/esop.init"
  destdir="/data/esop_codes/"
else
  echo "agent or server ?"
  exit 1
fi
autorpm="${basedir}/rpm_build/autorpm"
args="tarball"

filename=$( eval "${autorpm} ${args}" )
check_rc "make rpm"

ls "${filename}" >/dev/null 2>&1
check_rc "check path: ${filename}"

/bin/cp -f "${filename}" "${destdir}/"
check_rc "copy to ${destdir}/${filename##*/}"

/bin/cp -f "${specfile}" "${destdir}/"
check_rc "copy to ${destdir}/${specfile##*/}"

/bin/cp -f "${initfile}" "${destdir}/"
check_rc "copy to ${destdir}/${initfile##*/}"
