#!/usr/bin/env bash

#
# Inner Plugin:  periodic post plugin list.
#

# BASE_DIR DEF
[ -z ${BASE_DIR} ] && {
        path=$( cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
        BASE_DIR=${BASE_DIR%/*}
}
if [ -f ${BASE_DIR}/bin/include ] && [ -s ${BASE_DIR}/bin/include ]; then
        source ${BASE_DIR}/bin/include 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo "load include file failed with status $rc"
                exit 1
        }   
else
        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
        exit 1
fi

# Return Codes
STATE_SUCC=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_NOOP=4

# Set Default
EXIT_STATUS=0
LEVEL=          ### { succ | warn | crit | unknown }
TYPE=           ### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# check function here
check() {
  local jobid_plugin=$( ${PLUTIL} unique_digest )      ### set random/unique jid
  local jobid_config=$( ${PLUTIL} unique_digest )      ### set random/unique jid

  ${POSTLOG_SH} -t plugin -j "${jobid_plugin}" >/dev/null 2>&1
  rc1=$?
  ${POSTLOG_SH} -t config -j "${jobid_config}" >/dev/null 2>&1
  rc2=$?
  if [ "${rc1}" == "0" ] && [ "${rc2}" == "0" ]; then
  	EXIT_STATUS="${STATE_SUCC}"
  	LEVEL="succ"
  	TYPE="str"
  	CONTENT="post config data succeed | post {plugin/config} configuration json succeed | plugin jobid: ${jobid_plugin} ### config jobid: ${jobid_config}";
  else
	EXIT_STATUS="${STATE_WARNING}"
        LEVEL="warn"
        TYPE="str"
        CONTENT="post config data failed | post {plugin/config} configuration json failed (${rc1},${rc2}) | plugin jobid: ${jobid_plugin} ### config jobid: ${jobid_config}"
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}  
