#!/usr/bin/env bash

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"

# BASE DIR DEF
BASE_DIR=$( cd $(dirname $0) && pwd)

# DIR DEF
FILES_DIR="${BASE_DIR}/files"
LOGS_DIR="${BASE_DIR}/logs"
VAR_DIR="${BASE_DIR}/var"

# FILE DEF
LOGFILE="${LOGS_DIR}/${0##*/}.log"


# UPGRADE DEF
SYS_HOSTS="/etc/hosts"
ESOP_PATH="/usr/local/esop/agent"
MOLE_PATH="${ESOP_PATH}/mole"
MOLECONF_PATH="${MOLE_PATH}/conf"
PROXYETC_PATH="${ESOP_PATH}/etc"
MOLECONF_SAVE="${VAR_DIR}/conf"
PROXYETC_SAVE="${VAR_DIR}/etc"
ESOP_RPMNAME="esop"
PGMAIL_RPMNAME="esop-plugingroup-mail"
REQUIRED_UTILS=(
	"/bin/awk"
	"/bin/sed"
	"/bin/rpm"
	"/bin/cp"
	"/bin/rm"
)
RECOVERY_MOLECOMM_FILES=(
        ".mole.ini"
        "cpu_usage.ini"
        "disk_fs.ini"
        "disk_space.ini"
        "memory.ini"
        "notify_oom.ini"
        "notify_syslogin.ini"
        "port.ini"
        "sysload.ini"
        "system_dyninfo.ini"
        "system_fixinfo.ini"
        "tcp_conn.ini"
        "traffic.ini"
)
RECOVERY_MOLESPEC_FILES=(
	"disk_iostat.ini"
	"process.ini"
)
RECOVERY_PROXY_FILES=(
	"etm_agent.ini"
	"etm_phptd.ini"
)
CLEANED_FILES=(
	"/tmp/.etm_phptd.ini.saveold"
	"/tmp/.etm_agent.ini.saveold"
	"/tmp/.mole.ini.saveold"
)
CLEANED_LINKS=(
	"/usr/bin/mole"
	"/usr/bin/esop"
)



# FUNC DEF

# Terminal color
echo_green() {
  local content=$*
  echo -e "\033[1;32m${content}\033[0m\c "
}
echo_yellow() {
  local content=$*
  echo -e "\033[1;33m${content}\033[0m\c "
}
echo_red() {
  local content=$* 
  echo -e "\033[1;31m${content}\033[0m\c "
}

_check() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  succed!  ${*} " | tee -a $LOGFILE
  else
        echo -e " -- $(date +%F_%T)  failed!  ${*} " | tee -a $LOGFILE
        exit 1
  fi  
}

_notice() {
	echo -e " -- $(date +%F_%T)  notice!  ${*} " | tee -a $LOGFILE
}

_info() {
	echo -e " -- $(date +%F_%T)  info!  ${*} " | tee -a $LOGFILE
}

is_esop_installed() {
	if /bin/rpm -qi $ESOP_RPMNAME >/dev/null 2>&1; then
		return 0
	else
		return 1
	fi
}

is_pgmail_installed() {
	if /bin/rpm -qi $PGMAIL_RPMNAME >/dev/null 2>&1; then
		return 0
	else
		return 1
	fi
}

get_esopver() {
	local result=
	if is_esop_installed;  then
		result=$( /bin/rpm -q --queryformat "%{version}-%{release}" $ESOP_RPMNAME 2>&- )
	fi
	echo -en "${result}"
}

get_pgmailver() {
	local result=
	if is_pgmail_installed; then
        	result=$( /bin/rpm -q --queryformat "%{version}-%{release}" $PGMAIL_RPMNAME 2>&- )
        fi
        echo -en "${result}"
}

get_osrelease() {
	local lsb_release="/usr/bin/lsb_release" file1="/etc/redhat-release" file2="/etc/issue" 
	local result=
	if [ -f "${lsb_release}" -a -x "${lsb_release}" ]; then
		result=$( $lsb_release -d 2>&- | awk '(/Description:/) {gsub("Description:[ \t]*","",$0);print;exit;}' )
	elif [ -f "${file1}" -a -s "${file1}" ]; then
		result=$( head -n1 "${file1}" )
	elif [ -f "${file2}" -a -s "${file2}" ]; then
		result=$( head -n1 "${file2}" )
	fi
	echo -en "${result}"
}

get_rhel56() {
	local osrelease="$(get_osrelease)"
	local result=
	if ( echo "${osrelease}" | grep -E -i "release[ \t]*5" ) >/dev/null 2>&1; then
		result="rhel5"
	elif ( echo "${osrelease}" | grep -E -i "release[ \t]*6" ) >/dev/null 2>&1; then
		result="rhel6"
	fi
	echo -en "${result}"
}

read_ini_config() {
	local config_file=$1  section=$2  key=$3
	local result=
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		result=$( cat ${config_file} | tr '\t' ' ' |\
                        awk -F"=" '\
                                ($0~/^ *\[ *'${section}' *\] *$/){k=1;x=1;next}\
                                ( x==1 && $0~/^ *\[ *.* *\] *$/ && $0!~/^ *\[ *'${section}' *\] *$/ ){exit}\
                                ( k==1 && x==1 && $1~/^'${key}'\>/ ){gsub("^'${key}' *=","",$0);print;exit;}' 2>&- |\
                         sed -e 's/^[ \t]*//; s/[ \t]*$//;' 2>&- )
	fi
	echo -en "${result}"
}

update_ini_config() {
	local config_file=$1  section=$2  key=$3;
	shift 3;
	local value=$*
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		local linenum=$( cat ${config_file} | tr '\t' ' ' |\
			awk -F"=" '\
				($0~/^ *\[ *'${section}' *\] *$/){k=1;x=1;next}\
				( x==1 && $0~/^ *\[ *.* *\] *$/ && $0!~/^ *\[ *'${section}' *\] *$/ ){exit}\
				( k==1 && x==1 && $1~/^'${key}'\>/ ){print NR;exit;}' )
		if [ -z "${linenum}" ]; then
			return 2
		else
			sed -i ''${linenum}'c'"${key}"' = '"${value}"'' "${config_file}" >/dev/null 2>&1
			if [ "$?" == "0" ]; then
				return 0
			else
				return 1
			fi
		fi
	else
		return 3
	fi
}

add_ini_config() {
	local config_file=$1  section=$2  key=$3;
	shift 3;
	local value=$*
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		local section_linenum=$( cat ${config_file} | tr '\t' ' ' |\
			awk '($0~/^ *\[ *'${section}' *\] *$/){print NR;exit;}' )
		if [ -z "${section_linenum}" ]; then
			return 2
		else
			sed -i ''${section_linenum}'a'"${key}"' = '"${value}"'' "${config_file}" >/dev/null 2>&1
			if [ "$?" == "0" ]; then
				return 0
			else
				return 1
			fi
		fi
	else
		return 3
	fi
}

del_ini_config() {
	local config_file=$1  section=$2  key=$3;
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		local linenum=$( cat ${config_file} | tr '\t' ' ' |\
			awk -F"=" '\
				($0~/^ *\[ *'${section}' *\] *$/){k=1;x=1;next}\
				( x==1 && $0~/^ *\[ *.* *\] *$/ && $0!~/^ *\[ *'${section}' *\] *$/ ){exit}\
				( k==1 && x==1 && $1~/^'${key}'\>/ ){print NR;exit;}' )
		if [ -z "${linenum}" ]; then
			return 2
		else
			sed -i ''${linenum}'d' "${config_file}" >/dev/null 2>&1
			if [ "$?" == "0" ]; then
				return 0
			else
				return 1
			fi
		fi
	else
		return 3
	fi
}

save_configs() {
	/bin/cp -af "${MOLECONF_PATH}" "${MOLECONF_SAVE}"
	_check "save ${MOLECONF_PATH}"

	/bin/cp -af "${PROXYETC_PATH}" "${PROXYETC_SAVE}"
	_check "save ${PROXYETC_PATH}"
}

rpm_uninstall() {
	/bin/rpm -e $ESOP_RPMNAME 2>&-
	_check "uninstall $ESOP_RPMNAME"

	/bin/rpm -e $PGMAIL_RPMNAME 2>&-
	_check "uninstall $PGMAIL_RPMNAME"
}

clean_oldfiles() {
	for file in ${CLEANED_FILES[*]}
	do
		if [ -f "${file}" ]; then
			/bin/rm -f "${file}"
			_check "remove ${file}"
		else
			_info "file $file not exist, nothing to do"
		fi
	done
	for file in ${CLEANED_LINKS[*]}
	do
		if [ -L "${file}" ]; then
			/bin/rm -f "${file}"
			_check "remove ${file}"
		else
			_info "link $file not exist, nothing to do"
		fi
	done
}

rpm_install() {
:
}

restore_configs() {
:
}

upgrade_configs() {
:
}

upgrade_cksum() {
:
}


#
### Main Body Begin ...
#

if [ "$(/usr/bin/id -u 2>&-)" != "0" ]; then
  echo_red "root privilege required!";echo
  exit 1
fi

ESOP_VERSION=$( get_esopver )
PGMAIL_VERSION=$( get_pgmailver )

if [ -z "$ESOP_VERSION" ]; then
  echo_red "rpm $ESOP_RPMNAME not installed!";echo
  exit 1
fi
