#!/usr/bin/env bash

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"

# BASE DIR DEF
BASE_DIR=$( cd $(dirname $0) && pwd)

# DIR DEF
FILES_DIR="${BASE_DIR}/files"
EL6_64DIR="${FILES_DIR}/esop/rhel6_x86_64"
EL5_64DIR="${FILES_DIR}/esop/rhel5_x86_64"
EL5_32DIR="${FILES_DIR}/esop/rhel5_i386"
PGMAILDIR="${FILES_DIR}/pgmail"
LOGS_DIR="${BASE_DIR}/logs"
VAR_DIR="${BASE_DIR}/var"

# FILE DEF
LOGFILE="${LOGS_DIR}/${0##*/}.log"
EL6_64FILE="${EL6_64DIR}/esop-1.0.1-rhel6.x86_64.rpm"
EL5_64FILE="${EL5_64DIR}/esop-1.0.1-rhel5.x86_64.rpm"
EL5_32FILE="${EL5_32DIR}/esop-1.0.1-rhel5.i386.rpm"
PGMAILFILE="${PGMAILDIR}/esop-plugingroup-mail-0.1-rhel.noarch.rpm"

ESOP_MD5LST="${FILES_DIR}/esop/md5sum.lst"
PGMAIL_MD5LST="${FILES_DIR}/pgmail/md5sum.lst"

# UPGRADE DEF
SYS_HOSTS="/etc/hosts"
ESOP_PATH="/usr/local/esop"
MOLE_PATH="${ESOP_PATH}/agent/mole"
MOLECONF_PATH="${MOLE_PATH}/conf"
PROXYETC_PATH="${ESOP_PATH}/agent/etc"
MOLECONF_SAVE="${VAR_DIR}/conf"
PROXYETC_SAVE="${VAR_DIR}/etc"
ESOP_RPMNAME="esop"
PGMAIL_RPMNAME="esop-plugingroup-mail"
REQUIRED_UTILS=(
	"/bin/awk"
	"/bin/sed"
	"/bin/rpm"
	"/bin/cp"
	"/bin/rm"
	"/bin/mv"
	"/usr/bin/md5sum"
)
RESTORE_MOLECOMM_FILES=(
        ".mole.ini"
        "cpu_usage.ini"
        "disk_fs.ini"
        "disk_space.ini"
        "memory.ini"
        "notify_oom.ini"
        "notify_syslogin.ini"
        "port.ini"
        "sysload.ini"
        "system_dyninfo.ini"
        "system_fixinfo.ini"
        "tcp_conn.ini"
        "traffic.ini"
)
RESTORE_MOLESPEC_FILES=(
	"disk_iostat.ini"
	"process.ini"
)
RESTORE_PROXY_FILES=(
	"etm_agent.ini"
	"etm_phptd.ini"
)
RESTORE_PGMAIL_FILES=(
	"http_svr.ini"
	"imap_svr.ini"
	"smtp_svr.ini"
	"pop_svr.ini"
	"dns_svr.ini"
	"emp_mailqueue.ini"
)
CLEANED_FILES=(
	"/tmp/.etm_phptd.ini.saveold"
	"/tmp/.etm_agent.ini.saveold"
	"/tmp/.mole.ini.saveold"
)
CLEANED_LINKS=(
	"/usr/bin/mole"
	"/usr/bin/esop"
)



# FUNC DEF

# Terminal color
echo_green() {
  local content=$*
  echo -e "\033[1;32m${content}\033[0m\c "
}
echo_yellow() {
  local content=$*
  echo -e "\033[1;33m${content}\033[0m\c "
}
echo_red() {
  local content=$* 
  echo -e "\033[1;31m${content}\033[0m\c "
}

_check() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  [$(echo_green "SUCC")]  ${*} " | tee -a $LOGFILE
  else
        echo -e " -- $(date +%F_%T)  [$(echo_red "FAIL")]  ${*} " | tee -a $LOGFILE
        exit 1
  fi  
}

_notice() {
	echo -e " -- $(date +%F_%T)  [$(echo_yellow "NOTE")]  ${*} " | tee -a $LOGFILE
}

_info() {
	echo -e " -- $(date +%F_%T)  [$(echo_green "INFO")]  ${*} " | tee -a $LOGFILE
}

util_check() {
	local total=0 err=0
	local lacklst=

	for util in ${REQUIRED_UTILS[*]}
	do
		((total++))
		if [ -f "${util}" -a -x "${util}" ]; then
			:
		else
			((err++))
			lacklst="${lacklst} ${util}"
		fi
	done

	if [ $err -ne 0 ]; then
		echo -en "${lacklst}"
	fi
}

is_esop_installed() {
	if /bin/rpm -qi $ESOP_RPMNAME >/dev/null 2>&1; then
		return 0
	else
		return 1
	fi
}

is_pgmail_installed() {
	if /bin/rpm -qi $PGMAIL_RPMNAME >/dev/null 2>&1; then
		return 0
	else
		return 1
	fi
}

get_esopver() {
	local result=
	if is_esop_installed;  then
		result=$( /bin/rpm -q --queryformat "%{version}-%{release}" $ESOP_RPMNAME 2>&- )
	fi
	echo -en "${result}"
}

get_pgmailver() {
	local result=
	if is_pgmail_installed; then
        	result=$( /bin/rpm -q --queryformat "%{version}-%{release}" $PGMAIL_RPMNAME 2>&- )
        fi
        echo -en "${result}"
}

get_osrelease() {
	local lsb_release="/usr/bin/lsb_release" file1="/etc/redhat-release" file2="/etc/issue" 
	local result=
	if [ -f "${lsb_release}" -a -x "${lsb_release}" ]; then
		result=$( $lsb_release -d 2>&- | awk '(/Description:/) {gsub("Description:[ \t]*","",$0);print;exit;}' )
	elif [ -f "${file1}" -a -s "${file1}" ]; then
		result=$( head -n1 "${file1}" )
	elif [ -f "${file2}" -a -s "${file2}" ]; then
		result=$( head -n1 "${file2}" )
	fi
	echo -en "${result}"
}

get_rhel56() {
	local osrelease="$(get_osrelease)"
	local result=
	if ( echo "${osrelease}" | grep -E -i "release[ \t]*5" ) >/dev/null 2>&1; then
		result="rhel5"
	elif ( echo "${osrelease}" | grep -E -i "release[ \t]*6" ) >/dev/null 2>&1; then
		result="rhel6"
	fi
	echo -en "${result}"
}

read_ini_config() {
	local config_file=$1  section=$2  key=$3
	local result=
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		result=$( cat ${config_file} | tr '\t' ' ' |\
                        awk -F"=" '\
                                ($0~/^ *\[ *'${section}' *\] *$/){k=1;x=1;next}\
                                ( x==1 && $0~/^ *\[ *.* *\] *$/ && $0!~/^ *\[ *'${section}' *\] *$/ ){exit}\
                                ( k==1 && x==1 && $1~/^'${key}'\>/ ){gsub("^'${key}' *=","",$0);print;exit;}' 2>&- |\
                         sed -e 's/^[ \t]*//; s/[ \t]*$//;' 2>&- )
	fi
	echo -en "${result}"
}

update_ini_config() {
	local config_file=$1  section=$2  key=$3;
	shift 3;
	local value=$*
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		local linenum=$( cat ${config_file} | tr '\t' ' ' |\
			awk -F"=" '\
				($0~/^ *\[ *'${section}' *\] *$/){k=1;x=1;next}\
				( x==1 && $0~/^ *\[ *.* *\] *$/ && $0!~/^ *\[ *'${section}' *\] *$/ ){exit}\
				( k==1 && x==1 && $1~/^'${key}'\>/ ){print NR;exit;}' )
		if [ -z "${linenum}" ]; then
			return 2
		else
			sed -i ''${linenum}'c'"${key}"' = '"${value}"'' "${config_file}" >> $LOGFILE 2>&1
			if [ "$?" == "0" ]; then
				return 0
			else
				return 1
			fi
		fi
	else
		return 3
	fi
}

add_ini_config() {
	local config_file=$1  section=$2  key=$3;
	shift 3;
	local value=$*
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		local section_linenum=$( cat ${config_file} | tr '\t' ' ' |\
			awk '($0~/^ *\[ *'${section}' *\] *$/){print NR;exit;}' )
		if [ -z "${section_linenum}" ]; then
			return 2
		else
			sed -i ''${section_linenum}'a'"${key}"' = '"${value}"'' "${config_file}" >> $LOGFILE 2>&1
			if [ "$?" == "0" ]; then
				return 0
			else
				return 1
			fi
		fi
	else
		return 3
	fi
}

del_ini_config() {
	local config_file=$1  section=$2  key=$3;
	if [ -f "${config_file}" -a -s "${config_file}" ]; then
		local linenum=$( cat ${config_file} | tr '\t' ' ' |\
			awk -F"=" '\
				($0~/^ *\[ *'${section}' *\] *$/){k=1;x=1;next}\
				( x==1 && $0~/^ *\[ *.* *\] *$/ && $0!~/^ *\[ *'${section}' *\] *$/ ){exit}\
				( k==1 && x==1 && $1~/^'${key}'\>/ ){print NR;exit;}' )
		if [ -z "${linenum}" ]; then
			return 2
		else
			sed -i ''${linenum}'d' "${config_file}" >> $LOGFILE 2>&1
			if [ "$?" == "0" ]; then
				return 0
			else
				return 1
			fi
		fi
	else
		return 3
	fi
}

save_configs() {
	/bin/cp -af "${MOLECONF_PATH}" "${MOLECONF_SAVE}" >> $LOGFILE 2>&1
	_check "save mole configs"

	/bin/cp -af "${PROXYETC_PATH}" "${PROXYETC_SAVE}" >> $LOGFILE 2>&1
	_check "save proxy configs"
}

rpm_uninstall() {
	if [ -z "${PGMAIL_VERSION}" ]; then
		_notice "uninstall $PGMAIL_RPMNAME skip, as not installed before"
	else
		/bin/rpm -e $PGMAIL_RPMNAME >> $LOGFILE 2>&1
		_check "uninstall $PGMAIL_RPMNAME"
	fi

	/bin/rpm -e $ESOP_RPMNAME  >> $LOGFILE 2>&1
	_check "uninstall $ESOP_RPMNAME"

}

clean_oldfiles() {
	if [ -d "${ESOP_PATH}" ]; then
		/bin/mv -f "${ESOP_PATH}" "${ESOP_PATH}_${ESOP_VERSION}_${OS_RHEL56}_$(date +%s)" >> $LOGFILE 2>&1
		_check "backup old installation directories"

	fi
	for file in ${CLEANED_FILES[*]}
	do
		if [ -f "${file}" ]; then
			/bin/rm -f "${file}" >> $LOGFILE 2>&1
			_check "remove ${file}"
		else
			_info "file $file not exist, nothing to do"
		fi
	done
	for file in ${CLEANED_LINKS[*]}
	do
		if [ -L "${file}" ]; then
			/bin/rm -f "${file}" >> $LOGFILE 2>&1
			_check "remove ${file}"
		else
			_info "link $file not exist, nothing to do"
		fi
	done
}

rpm_install() {
	
	local rpmfile=

	if [ "${OS_RHEL56}" == "rhel5" ]; then
		if [ "$(/bin/uname -a 2>&- | grep -E -o "x86_64")" != "" ]; then
			rpmfile="${EL5_64FILE}"
		else
			rpmfile="${EL5_32FILE}"
		fi
	elif [ "${OS_RHEL56}" == "rhel6" ]; then
		if [ "$(/bin/uname -a 2>&- | grep -E -o "x86_64")" != "" ]; then
			rpmfile="${EL6_64FILE}"
		fi
	fi

	/bin/rpm -ivh "${rpmfile}"  >> $LOGFILE 2>&1
	_check "install ${ESOP_RPMNAME}"

	if [ -z "${PGMAIL_VERSION}" ]; then
		_notice "install $PGMAIL_RPMNAME skip, as not installed before"
	else
		/bin/rpm -ivh ${PGMAILFILE} >> $LOGFILE 2>&1
		_check "install ${PGMAIL_RPMNAME}"
	fi
}

restore_configs() {
	
	# restore mole common config files
	for file in ${RESTORE_MOLECOMM_FILES[*]}
	do
		/bin/cp -f "${MOLECONF_SAVE}/${file}"  "${MOLECONF_PATH}/${file}"
        	_check "restore mole common configs ${file}"
	done

	# restore mole special config files if esop version = 1.0-beta2
	if [ "${ESOP_VERSION}" == "1.0-beta2" ]; then
		_notice "restore mole special configs continue, as esop version ${ESOP_VERSION}"
		for file in ${RESTORE_MOLESPEC_FILES[*]}
		do
			/bin/cp -f "${MOLECONF_SAVE}/${file}"  "${MOLECONF_PATH}/${file}"
			_check "restore mole special configs ${file}"
		done
	else
		_notice "restore mole special configs skip, as esop version ${ESOP_VERSION}"
	fi

	# restore pgmail config files if pgmail installed
	if [ -z "${PGMAIL_VERSION}" ]; then
		_notice "restore $PGMAIL_RPMNAME configs skip, as not installed before"
	else
		for file in ${RESTORE_PGMAIL_FILES[*]}
		do
			/bin/cp -f "${MOLECONF_SAVE}/${file}"  "${MOLECONF_PATH}/${file}"
			_check "restore $PGMAIL_RPMNAME configs ${file}"
		done
	fi

	# restore proxy config files
	for file in ${RESTORE_PROXY_FILES[*]}
	do
		/bin/cp -f "${PROXYETC_SAVE}/${file}"  "${PROXYETC_PATH}/${file}"
        	_check "restore proxy configs"
	done
}

upgrade_configs() {
	local etm_phptd_ini="${PROXYETC_PATH}/etm_phptd.ini"
	local mole_ini="${MOLECONF_PATH}/.mole.ini"
	local cpu_usage_ini="${MOLECONF_PATH}/cpu_usage.ini"
	local notify_oom_ini="${MOLECONF_PATH}/notify_oom.ini"
	local tcp_conn_ini="${MOLECONF_PATH}/tcp_conn.ini"

	# process file: etm_phptd_ini
	sed -i 's/max_dest_buffer_len = 10000/max_dest_buffer_num = 10000/' ${etm_phptd_ini} >> $LOGFILE 2>&1
	_check "rename max_dest_buffer_len as max_dest_buffer_num"

	del_ini_config ${etm_phptd_ini} agent_client noop_interval
	_check "remove noop_interval"
	
	del_ini_config ${etm_phptd_ini} agent_client retry_connect_dest_interval
	_check "remove retry_connect_dest_interval"

	add_ini_config ${etm_phptd_ini} agent_client connect_dest_interval 3
	_check "add connect_dest_interval = 3"

	# process file: mole.ini
	local smtp_server=$( read_ini_config ${mole_ini} sendmail smtp_server )
	if [ "${smtp_server}" == "esop.eyou.net" ]; then
		update_ini_config ${mole_ini} sendmail smtp_server "mole.eyousop.com"
		_check "update sendmail -> smtp_server = mole.eyousop.com"
	else
		_info "no need to update sendmail -> smtp_server ($smtp_server)"
	fi

	local logfile_reserve_time=$( read_ini_config ${mole_ini} mole_clear_overdue logfile_reserve_time )
	if [ "${logfile_reserve_time}" == "180" ]; then
		update_ini_config ${mole_ini} mole_clear_overdue logfile_reserve_time "30"
		_check "update mole_clear_overdue -> logfile_reserve_time = 30"
	else
		_info "no need to update mole_clear_overdue -> logfile_reserve_time ($logfile_reserve_time)"
	fi

	local debug=$( read_ini_config ${mole_ini} default debug )
	if [ "${debug}" == "no" ]; then
		update_ini_config ${mole_ini} default debug "yes"
		_check "update default -> debug = yes"
	else
		_info "no need to update default -> debug ($debug)"
	fi

	add_ini_config ${mole_ini} mole_log_rotate take_over_proxylog "yes"
	_check "add mole_log_rotate -> take_over_proxylog = yes"

	# process file: cpu_usage.ini
	local maxerr_times=$( read_ini_config ${cpu_usage_ini} cpu_usage maxerr_times )
	if [ "${maxerr_times}" == "3" ]; then
		update_ini_config ${cpu_usage_ini} cpu_usage maxerr_times "5"
		_check "update cpu_usage -> maxerr_times = 5"
	else
		_info "no need to update cpu_usage -> maxerr_times ($maxerr_times)"
	fi

	# process file: notify_oom.ini
	local mail_notify=$( read_ini_config ${notify_oom_ini} notify_oom mail_notify )
	if [ "${mail_notify}" == "all" ]; then
		update_ini_config ${notify_oom_ini} notify_oom mail_notify "default"
		_check "update notify_oom -> mail_notify = default"
	else
		_info "no need to update notify_oom -> mail_notify ($mail_notify)"
	fi

	# process file: tcp_conn.ini
	local exec_tmout=$( read_ini_config ${tcp_conn_ini} tcp_conn exec_tmout )
	if [ "${exec_tmout}" == "2min" ]; then
		update_ini_config ${tcp_conn_ini} tcp_conn exec_tmout "5min"
		_check "update tcp_conn -> exec_tmout = 5min"
	else
		_info "no need to update tcp_conn -> exec_tmout ($exec_tmout)"
	fi

}

upgrade_cksum() {
	local md5sum_2=  mismatch_lst=
	local total=0  err=0

	while read md5sum_1 filepath
	do
		((total++))
		md5sum_2=$( /usr/bin/md5sum "${filepath}" 2>&- | awk '{print $1;exit}' )
		if [ "${md5sum_2}" == "${md5sum_1}" ]; then
			_info "md5 check for ${filepath} passed!" >/dev/null
		else
			((err++))
			mismatch_lst="${mismatch_lst} ${filepath}"
			_notice "md5 check for ${filepath} not passed!" >/dev/null
		fi
	done < "${ESOP_MD5LST}"

	if [ -z "${PGMAIL_VERSION}" ]; then
		_notice "md5 check for $PGMAIL_RPMNAME skip, as not installed before" >/dev/null
	else
		while read md5sum_1 filepath
		do
			((total++))
			md5sum_2=$( /usr/bin/md5sum "${filepath}" 2>&- | awk '{print $1;exit}' )
			if [ "${md5sum_2}" == "${md5sum_1}" ]; then
				_info "md5 check for ${filepath} passed!" >/dev/null
			else
				((err++))
				mismatch_lst="${mismatch_lst} ${filepath}"
				_notice "md5 check for ${filepath} not passed!" >/dev/null
			fi
		done < "${PGMAIL_MD5LST}"
	fi

	if [ $err -ne 0 ]; then
		echo -en "${err}/${total} files failed! ${mismatch_lst}"
		return 1
	else
		echo -en "${total}/${total} files cksum passed!"
		return 0
	fi
}

check_syshosts() {
	if grep -E "esop.eyou.net|mole.eyousop.com" $SYS_HOSTS >/dev/null 2>&1; then
		_notice "! $(echo_red "Please remove [esop.eyou.net] or [mole.eyousop.com] from $SYS_HOSTS") !"
	else
		_info "no need to remove dns-ip map from $SYS_HOSTS"
	fi
}

#
### Main Body Begin ...
#


### previous check
if [ "$(/usr/bin/id -u 2>&-)" != "0" ]; then
	echo_red "root privilege required!";echo
	exit 1
fi

ESOP_VERSION=$( get_esopver )
PGMAIL_VERSION=$( get_pgmailver )
if [ -z "$ESOP_VERSION" ]; then
	echo_red "rpm $ESOP_RPMNAME not installed!";echo
	exit 1
else
  	if [ "${ESOP_VERSION}" == "1.0-beta1" -o "${ESOP_VERSION}" == "1.0-beta2" ]; then
		:
	else
		echo_red "only $ESOP_RPMNAME 1.0-beta1 or 1.0-beta2 supported! nower version $ESOP_VERSION";echo;
		exit 1
	fi
fi

OS_RHEL56=$( get_rhel56 )
if [ -z "$OS_RHEL56" ]; then
	echo_red "can't get os release 5/6 ?";echo
	exit 1
fi

UTIL_LACK=$( util_check )
if [ -n "${UTIL_LACK}" ]; then
	echo_red "lack utils: [${UTIL_LACK}]";echo
	exit 1
fi

### agent upgrade
_info
_info
_info "esop upgrade start"

save_configs
rpm_uninstall
clean_oldfiles
rpm_install
restore_configs
upgrade_configs

### at last
info=$( upgrade_cksum )
_check "$info"
check_syshosts

_info "esop upgrade finished"
_info
_info
