#!/bin/bash

path=$(cd $(dirname $0) && pwd)
basedir=${path%/*}

specfile=
if (uname -r | grep -q el5)>/dev/null 2>&1; then
	specfile="${path}/esop_rhel5.spec"
elif (uname -r | grep -q el6)>/dev/null 2>&1; then
	specfile="${path}/esop_rhel6.spec"
fi


clean(){
  rm -rf "${path}"/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} 2>&-
  mkdir -p "${path}"/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} 2>&-
}
clean
[ "$1" == "clean" ] && exit 0

[ -f "/usr/bin/rpmbuild" -a -x "/usr/bin/rpmbuild" ] || {
        echo "/usr/bin/rpmbuild not prepared"
        exit 1
}

if [ -f "${specfile}" -a -s "${specfile}" ]; then
  name="$(awk '($1~/^Name:/){print $2}' ${specfile} 2>&-)"
  version="$(awk '($1~/^Version:/){print $2}' ${specfile} 2>&-)"
  release="$(awk '($1~/^Release:/){print $2}' ${specfile} 2>&-)"
  tgzname="${name}-${version}-${release}.tgz"
else
  echo "${specfile} not prepared."
  exit 1
fi

esop_dir="/usr/local/esop"
if [ -d "${esop_dir}" ]; then
	/bin/cp -a "${esop_dir}" "${path}/SOURCES/${name}-${version}"
	/bin/rm -rf "${esop_dir}"
	cd "${path}/SOURCES/"
	/bin/tar -czf "${path}/SOURCES/$tgzname" "${name}-${version}"
	/bin/rm -rf "${path}/SOURCES/${name}-${version}"
else
	echo "${esop_dir} not prepared, mkrpm exit."
	exit  1
fi

cat > ~/.rpmmacros <<EOF
%_topdir ${path}/
%debug_package %{nil}
EOF

/bin/cp "${specfile}" "${path}/SPECS/${name}.spec"
if [ ! -f "${path}/SPECS/${name}.spec" ]; then
	echo "${name}.spec file not ready. exit"
	exit 1
fi
/bin/cp "${path}/${name}.init" "${path}/SOURCES/${name}.init"
if [ ! -f "${path}/SOURCES/${name}.init" ]; then
	echo "${name}.init file not ready. exit"
	exit 1
fi

/usr/bin/rpmbuild -bb "${path}/SPECS/${name}.spec"
echo;echo;
find "${path}"/RPMS/ -type f -iname "*.rpm" -print
