#!/bin/bash

path=$(cd $(dirname $0) && pwd)
basedir=${path%/*}

show_help(){
cat << HELP 
        ${0##*/}
        ${0##*/}  help
        ${0##*/}  clean
        ${0##*/}  tarball
HELP
exit 0
}

# first: clear old files
clean(){
  rm -rf "${path}"/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} 2>&-
  mkdir -p "${path}"/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} 2>&-
}
clean
[ "$1" == "clean" ] && exit 0

[ -f "/usr/bin/rpmbuild" -a -x "/usr/bin/rpmbuild" ] || {
	echo "/usr/bin/rpmbuild not prepared"
	exit 1
}

if [ "${1}" == "help" -o "${1}" == "-h" -o "${1}" == "?" ]; then
	show_help
elif [ "${1}" == "tarball" ]; then
	TARMODE=1
fi

name=$(awk -F: '($1~/Name/){print $2}' "${basedir}"/mole.spec 2>&-|tr -d ' \t')
version=$(awk -F: '($1~/Version/){print $2}' "${basedir}"/mole.spec 2>&-|tr -d ' \t')
source0=$(awk -F: '($1~/Source0/){print $2}' "${basedir}"/mole.spec 2>&-|tr -d ' \t')
source1=$(awk -F: '($1~/Source1/){print $2}' "${basedir}"/mole.spec 2>&-|tr -d ' \t')

mkdir -p "${path}"/SOURCES/${name}-${version}
cp -a "${basedir}"/{bin,conf,docs,mole,handler,log,opt,plugin,share,tmp} "${path}"/SOURCES/${name}-${version}/
cd "${path}"/SOURCES/
tar -czf "${source0}" ${name}-${version}
rm -rf "${path}"/SOURCES/${name}-${version}
if [ "${TARMODE}" == "1" ]; then
  echo "${path}/SOURCES/${source0}"
  exit 0
fi
cp -a "${basedir}"/${source1}   "${path}"/SOURCES/${source1}
cp -a "${basedir}"/mole.spec  "${path}"/SPECS/

cat > ~/.rpmmacros <<EOF
%_topdir ${path}/
%debug_package %{nil}
EOF

/usr/bin/rpmbuild -bb "${path}"/SPECS/mole.spec >/dev/null 2>&1
find "${path}"/RPMS/ -type f -iname "*.rpm" -print
