#!/usr/bin/env bash

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"

# BASE DIR DEF
BASE_DIR=$( cd $(dirname $0) && pwd)

# FILE DEF
SRC_FTMP="/var/tmp/.srcdir.md5db"
DST_FTMP="/var/tmp/.dstdir.md5db"
RESULT_F="/var/tmp/diffdir.result"
RESULT_CFG="/var/tmp/update.cfg"

# SEP DEF
SEPERATOR="~~~"

# REQUIRED_UTILS DEF
REQUIRED_UTILS=(
        "/bin/awk"
        "/bin/sed"
        "/usr/bin/md5sum"
	"/bin/sort"
	"/usr/bin/find"
	"/usr/bin/uniq"
	"/usr/bin/tee"
	"/usr/bin/column"
)


### Function Def

# Print Help
# 
show_help() {
cat << EOF
Usage:		./${0##*/}  srcdir(old)  dstdir(new)   [cfg] [prefix]
Example:	./${0##*/}  /etc/   /tmp/etc.1
Example:	./${0##*/}  srcdir  dstdir   cfg  "esop_web/files/"
EOF
exit 0
}

# Terminal color
#
echo_green() {
  local content=$*
  echo -e "\033[1;32m${content}\033[0m\c "
}
echo_yellow() {
  local content=$*
  echo -e "\033[1;33m${content}\033[0m\c "
}
echo_red() {
  local content=$*
  echo -e "\033[1;31m${content}\033[0m\c "
}

# Util Check 
#
util_check() {
  local lacklst=
  for util in ${REQUIRED_UTILS[*]}; do
	if [ ! -f "${util}" ] || [ ! -x "${util}" ]; then
		lacklst="${lacklst} ${util}"
	fi
  done
  [ -n "${lacklst}" ] && echo -en "${lacklst}"
}

# Build MD5 List for Directory
#
build_md5db() {
  local dirname="$1" md5dbfile="$2"
  if [ -z "${dirname}" ] || [ ! -d "${dirname}" ]; then
	echo_red "pls check your input [${dirname}]";echo
	exit 1
  fi

  if cd "${dirname}" >/dev/null 2>&1; then
  	if /usr/bin/find . -follow -type f -exec /usr/bin/md5sum {} \; > "${md5dbfile}" 2>/dev/null; then
		if cd "${BASE_DIR}" >/dev/null 2>&1; then
			return 0
		else
			echo_red "failed to return back [${BASE_DIR}]";echo
			exit 1
		fi
	else
		echo_red "failed to build [${dirname}] md5sum list";echo
		exit 1
	fi
  else
	echo_red "failed to change into [${dirname}]";echo
	exit 1
  fi
}

### Main Body Begin

# 0. check utils
UTIL_LACK=$( util_check )
if [ -n "${UTIL_LACK}" ]; then
        echo_red "lack utils: [${UTIL_LACK}]";echo
        exit 1
fi

# 1. remove last /
srcdir=$(echo "$1"|sed -e 's#/$##')
dstdir=$(echo "$2"|sed -e 's#/$##')
workmode="$3"
prefix="$4"
MODE=0

# 2. check input args 
if [ -z "${srcdir}" ] || [ -z "${dstdir}" ]; then
	show_help
elif [ ! -d "${srcdir}" ]; then
	echo_red "[${srcdir}] isn't an exist directory.";echo
	exit 1
elif [ ! -d "${dstdir}" ]; then
	echo_red "[${dstdir}] isn't an exist directory.";echo
	exit 1
fi

if [ "${workmode}" == "cfg" ]; then
	if [ -z "${prefix}" ]; then
		echo_red "prefix required on work mode=cfg";echo
		exit 1
	else
		MODE=1
	fi
else
	if [ -n "${workmode}" ]; then
		echo_red "workmode must be [cfg]";echo
		exit 1
	fi
fi

# 3. build md5sum list 
if build_md5db "${srcdir}" "${SRC_FTMP}"; then
	if build_md5db "${dstdir}" "${DST_FTMP}"; then
		src_files=$( /bin/awk '{$1="";print;}' "${SRC_FTMP}" 2>&- )
		dst_files=$( /bin/awk '{$1="";print;}' "${DST_FTMP}" 2>&- )
		echo "$(date +%F_%T) $(echo_green "[OK]") building md5sum list."
	else
		echo_red "build md5sum list for [${dstdir}] failed!";echo
		exit 1
	fi
else
	echo_red "build md5sum list for [${srcdir}] failed!";echo
	exit 1
fi

# 4. check add/delete
tmp_files=$( echo -e "${src_files}\n${dst_files}" | /bin/sort | /usr/bin/uniq -u )  ### \n is important
src_only=$( echo -e "${src_files}\n${tmp_files}"  | /bin/sort | /usr/bin/uniq -d | sed -e 's#^ .#'${srcdir}'#' )
dst_only=$( echo -e "${dst_files}\n${tmp_files}"  | /bin/sort | /usr/bin/uniq -d | sed -e 's#^ .#'${dstdir}'#' )
src_onlynum=$( echo -e "${src_only}" | sed -e '/^[ \t]*$/d' | awk -v RS="\n" 'END{print NR}' )
dst_onlynum=$( echo -e "${dst_only}" | sed -e '/^[ \t]*$/d' | awk -v RS="\n" 'END{print NR}' )
echo "$(date +%F_%T) $(echo_green "[OK]") check +/- files."

# 5. check modify 
mod_files=$( while read  -a line ; do awk -v s="${srcdir}" -v d="${dstdir}" '( $1!="'"${line[0]}"'" && $2=="'"${line[1]}"'" ) {gsub(/ *\.\//,"/",$2);printf "%s%s %s%s\n",s,$2,d,$2;exit;}' "${DST_FTMP}" ; done < "${SRC_FTMP}" )
mod_filesnum=$( echo -e "${mod_files}" | sed -e '/^[ \t]*$/d' | awk -v RS="\n" 'END{print NR}' )
echo "$(date +%F_%T) $(echo_green "[OK]") check <> files."

# 6. output result
echo;echo;
if [ "${MODE}" == "0" ]; then
	{ 
	echo -e "$(echo_green "Files Only in [${srcdir}] (${src_onlynum}):")"
	echo -e "${src_only}"
	echo -e "\n"
	echo -e "$(echo_green "Files Only in [${dstdir}] (${dst_onlynum}):")"
	echo -e "${dst_only}"
	echo -e "\n"
	echo -e "$(echo_green "Files Different (${mod_filesnum}):")"
	echo -e "${mod_files}" | /usr/bin/column -t
	echo -e "\n\n"
	} | /usr/bin/tee "${RESULT_F}"
	echo_green "Result File: ${RESULT_F}";echo;
elif [ "${MODE}" == "1" ]; then
	echo_green "Result File: ${RESULT_CFG}";echo;echo;
	{
	echo -e "[remove]"
	echo -e "${src_only}\n" | while read file
	do
		[ -z "${file}" ] && continue 1
		# file=$(echo -e "${file}" | awk -F "${srcdir}|${dstdir}" '{gsub(/^\//,"",$2);print $2;exit;}')
		# trim all space in result, this lead to can NOT deal with file with space, fuck that kind of file
		file=$(echo -e "${file}" | awk -F "${srcdir}|${dstdir}" '{gsub(/^\//,"",$2);gsub(" ","",$2);print $2;exit;}')
		echo -e "${file}"
	done
	echo

	echo -e "[add]"
	echo -e "${dst_only}\n" | while read file
	do
		[ -z "${file}" ] && continue 1
		# file=$(echo -e "${file}" | awk -F "${srcdir}|${dstdir}" '{gsub(/^\//,"",$2);print $2;exit;}')
		# trim all space in result, this lead to can NOT deal with file with space, fuck that kind of file
		file=$(echo -e "${file}" | awk -F "${srcdir}|${dstdir}" '{gsub(/^\//,"",$2);gsub(" ","",$2);print $2;exit;}')
		echo -e "${file}${SEPERATOR}${prefix}"
	done
	echo

	echo -e "[modify]"
	echo -e "${mod_files}\n" | while read file
	do
		[ -z "${file}" ] && continue 1
		# trim all space in result, this lead to can NOT deal with file with space, fuck that kind of file
		file=$(echo -e "${file}" | awk -F "${srcdir}|${dstdir}" '{gsub(/^\//,"",$2);gsub(" ","",$2);print $2;exit;}')
		echo -e "${file}${SEPERATOR}${prefix}"
	done
	echo
	} | /usr/bin/tee "${RESULT_CFG}"
	echo_green "Result File: ${RESULT_CFG}";echo;
fi
