#!/bin/bash

export PATH="${PATH}:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

### Global Vars Def
BASE_DIR="$(cd $(dirname $0); pwd)"
LOG_DIR="${BASE_DIR}/logs"
LOGFILE="${BASE_DIR}/logs/${0##*/}.log"

PATH_TARBALL="${BASE_DIR}/opt/balls"

PATH_ESOP="/usr/local/eyou/toolmail"



# Command Def

CMD_UNTAR="tar -xf"
CMD_UNTAR_BZ2="tar -jxf"
CMD_UNTAR_GZ="tar -zxf"
CMD_MAKE="make"
CMD_MAKE_J="make -j 2"


# Global Func Def

# - check_rc
check_rc() {
  if [ $? == 0 ]; then
        echo -e " -- $(date +%F_%T)  succed!  ${*} " | tee -a $LOGFILE
  else
        echo -e " -- $(date +%F_%T)  failed!  ${*} " | tee -a $LOGFILE
        exit 1
  fi
}

# -- build_apicode
build_apicode() {

  mkdir -p $PATH_ESOP/etc $PATH_ESOP/app $PATH_ESOP/log $PATH_ESOP/run
  check_rc "create directory etc app log run"

  # cp -a $PATH_TARBALL/implements $PATH_ESOP
  cp -a $PATH_TARBALL/implements/ $PATH_ESOP
  check_rc "copy implements to $PATH_ESOP"

  cp -a $PATH_TARBALL/app/bin/  $PATH_ESOP/app
  check_rc "copy app/bin to $PATH_ESOP"

  cp -a $PATH_TARBALL/app/inc/  $PATH_ESOP/app
  check_rc "copy app/inc to $PATH_ESOP"

  cp -a $PATH_TARBALL/app/lib/  $PATH_ESOP/app
  check_rc "copy app/lib to $PATH_ESOP"

  cp -a $PATH_TARBALL/app/sbin/  $PATH_ESOP/app
  check_rc "copy app/sbin to $PATH_ESOP"

  cp -fL $PATH_TARBALL/etc/etm_allow_ip.ini $PATH_ESOP/etc
  check_rc "copy etc/etm_allow_ip.ini to $PATH_ESOP"

  cp -fL $PATH_TARBALL/etc/etm_init_config $PATH_ESOP/etc
  check_rc "copy etc/etm_init_config to $PATH_ESOP"

  cp -fL $PATH_TARBALL/etc/etm_phptd.ini $PATH_ESOP/etc
  check_rc "copy etc/etm_phptd.ini to $PATH_ESOP"

  cp -fL $PATH_TARBALL/etc/eyou_toolmail.ini $PATH_ESOP/etc
  check_rc "copy etc/eyou_toolmail.ini to $PATH_ESOP"
}

# -- make_tarball 
make_tarball() {

  local tar_createdir="$BASE_DIR/esop_api"
  local tar_filename="esop_api.tar.gz"

  mkdir -p $tar_createdir/files
  check_rc "create local $tar_createdir/files"

  cp -a ${PATH_ESOP}/*  $tar_createdir/files
  check_rc "copy $PATH_ESOP to local $tar_createdir/files"

  cp -a $PATH_TARBALL/install $tar_createdir
  check_rc "copy $PATH_TARBALL/install  to local $tar_createdir/"

  cd $BASE_DIR
  check_rc "changing into $BASE_DIR"

  tar -czf $tar_filename ${tar_createdir##*/}
  check_rc "make tarball on $tar_createdir for $BASE_DIR/$tar_filename"

  rm -rf $tar_createdir
  check_rc "remove $tar_createdir"
}



### Main Body Begin ...

if [ "$(id -u)" != "0" ]; then
  echo " root privileges required! "
  exit 1
fi

echo -e "\n -- $(date +%F_%T) -- BUILD START -- \n\n" >> $LOGFILE


if [ -d "${PATH_ESOP}" ]; then
  rm -rf "${PATH_ESOP}"
  check_rc "remove ${PATH_ESOP}"
fi

if [ -d "${PATH_EXTRACT}" ]; then
  rm -rf "${PATH_EXTRACT}"
  check_rc "remove ${PATH_EXTRACT}"
fi


build_apicode
make_tarball


if [ -d "${PATH_ESOP}" ]; then
  rm -rf "${PATH_ESOP}"
  check_rc "remove ${PATH_ESOP}"
fi

if [ -d "${PATH_EXTRACT}" ]; then
  rm -rf "${PATH_EXTRACT}"
  check_rc "remove ${PATH_EXTRACT}"
fi

echo -e "\n -- $(date +%F_%T) -- BUILD END -- \n\n" >> $LOGFILE
